version: '3.8'

services:
  cvgenix-mongo:
    image: mongo:7.0
    container_name: cvgenix-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: kumarkumaran6253
      MONGO_INITDB_ROOT_PASSWORD: KumaranDB6253
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - cvgenix-net

  cvgenix-backend:
    image: kumaran0512/cvgenix-backend:latest
    container_name: cvgenix-backend
    restart: always
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://kumarkumaran6253:KumaranDB6253@cvgenix-mongo:27017/cvgenix?authSource=admin
      JWT_SECRET: cvgenix_jwt_super_secret_key_2026
      GOOGLE_CLIENT_ID: 369662873002-pbe6tlnnf65uou79vu861p53e9ca4pkh.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: GOCSPX-xxxxxxxxxxxxxxxx
      GOOGLE_CALLBACK_URL: http://34.227.92.150.nip.io/api/auth/google/callback
      CLIENT_URL: http://34.227.92.150.nip.io
    ports:
      - "5000:5000"
    depends_on:
      - cvgenix-mongo
    networks:
      - cvgenix-net

  cvgenix-frontend:
    image: kumaran0512/cvgenix-frontend:latest
    container_name: cvgenix-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - cvgenix-backend
    networks:
      - cvgenix-net

volumes:
  mongo-data:

networks:
  cvgenix-net:
    driver: bridge